### ISSUE TITLE
Additional data entry methods

### ISSUE THREAD

**Issue by dcatki** [holochain-open-dev/holoom#46] opened 2024-07-12 15:56 UTC
I've encountered an awkward bug with the faceit api - a match result's gone missing. If we're lucky this won't happen during our test run, but it's opened my eyes to a new of problems we'll want to solve: i.e. when the authority's hampered, what can be done to unstick the system.

One choice would be to ignore the missing result - but that could be rather outrageous if it significantly impacts the leaderboard.

If the information is available elsewhere (if even partially), then it might be worth allowing some method for entering the data manually. (Either via the authority, or some community intervention)

If we do "censor" a missing result, then the error should probably be published instead to at least account for it.

**Comment by 8e8b2c** [comment] 2024-08-07 10:09
Closing as duplicate of https://github.com/holochain-open-dev/holoom/issues/45

**Closed by 8e8b2c** 2024-08-07 10:09 UTC
Labels: duplicate
